### ISSUE TITLE
Player 0 health doesn't handled

### ISSUE THREAD

**Issue by mohorka** [hypnospinner/top-down-shooter#23]
## Player 0 health doesn't handled

**Description**

`PlayerController` doesn't handle situation when player has health 0 or lower. It should respawn player object dropping all abilities, weapon and AID kits aroun place of player death. Respawn can be made with special objects that "rememeber" player and item dropping can be handled with events.

**Comment by hypnospinner** [comment]
**Suggested solution**

Firstly it's considered that we have only 2 game mods in our final version of the game:
* Adventure (Sequence of 3-5 arenas, _goal_: kill all the enemies on the level)
* Survive (surviving waves of enemies)

In both of this modes end the game session is player's death. When player's health is less or equals 0 than it's considered that player is dead. When that happens game should stop and give player choice - leave current match (level) or try again. That's all that should happen.

**Addition**

We can generate with random, but very low chance special item that allows player to re-spawn once after first death on the re-spawn location of the level.

**Comment by hypnospinner** [comment]
Closed due to creation #34
