### ISSUE TITLE
Need to create "stop-point"

### ISSUE THREAD

**Issue by mohorka** [hypnospinner/top-down-shooter#31]
**Problem**
There is no end of play-zone,so when player goes beyond the edge of the field, it starts to endlessly fall down.

**Possible solution**
Somehow create barrier so as not to let the player get over the edge  of gamezone.

**Also**
Alternatively, maybe there should be created restart of the game, when player is off the gamezone.

**Comment by hypnospinner** [comment]
Closed due to creation of issue #34
