### ISSUE TITLE
Shotgun "Smasher"

### ISSUE THREAD

**Issue by hypnospinner** [hypnospinner/top-down-shooter#40]
**Describe what weapon you want to add (or enhance)**
Shotgun "Smasher" is powerful, but slow weapon that deals enormous damage to objects around

**How weapon should work?**
Mention all specific details like:
- How it shoots
   It shots slowly one-by-one
- What it shoots
   Powerful projectiles that can damage multiple objects at a time (several projectiles at one shot with scatter)
- How projectiles should work
   Go through objects counting number of penetrations and damaging them if possible (for limited amount of times)
   Alternative: With raycast damage first 3 (n) objects at a time

**Suggest stats for weapon**
_Fire Rate_: 0.8f
_Energy Consumption_: 10f

**How weapon should look like**
It should create red (angry) projectiles

**Comment by mohorka** [comment]
@hypnospinner,  почему Physics.Raycast принимает 6 объектов,я открыла документацию unity,там их 5,этот метод перегружен?
![1](https://user-images.githubusercontent.com/47743417/54864532-b419b800-4d69-11e9-84f4-17bbaac834c9.jpg)

**Comment by hypnospinner** [comment]
#42
